### ISSUE TITLE
Tests for the Emitter

### ISSUE THREAD

**Issue by sokra** [wasdk/wasmparser#11]
Maybe just expand the existing test suite to parser -> emitter -> check if equal.

**Comment by bmeurer** [comment]
We have e2e tests, which cover parser and disassembler.

**Comment by EricSL** [comment]
The emitter isn't tested, though. I did at one point start writing what Tobias suggests. If you disassemble and then emit wasm, you won't get a round trip due to different variable length encodings, but if you then disassemble and parse again you should get the same wasm text. You don't in all cases though because for one I didn't implement the emitter changes necessary for bulk memory support, and I think a few other test cases were broken as well. I didn't make this a priority because Yury was unaware of any users of the emitter, but if anyone thinks it might be useful doing this test would be a good start.

**Comment by bmeurer** [comment]
Oh, sorry, somehow i didn't read emitter, but disassembler in my head here.

**Comment by yurydelendik** [comment]
> Yury was unaware of any users of the emitter, but if anyone thinks it might be useful doing this test would be a good start

Looks like the emitter is the abandoned code at this moment. Closing in favor of #81
